### ISSUE TITLE
Error: No such validator 'required' exists vee-validate

### ISSUE THREAD

**Issue by timsayshey** [formvuelate/formvuelate-plugin-vee-validate#12]
I followed the instructions in the docs but for some reason I'm getting this error:
Error: No such validator 'required' exists vee-validate

https://formvuelate.js.org/guide/veevalidate.html#usage

Is there a codesandbox available where I can see this all working?

Thanks!

**Comment by marina-mosti** [comment]
Can you post which version numbers you're using and sample code please?

**Comment by timsayshey** [comment]
Sure. Here are the versions:

```
"@formvuelate/plugin-vee-validate": "^1.0.6",
"formvuelate": "^3.0.0-beta.7",
"vee-validate": "^4.2.2",
```

And here's the sample code: https://gist.github.com/timsayshey/8a1e604a08d44aef412d71d59b56cc49

**Comment by logaretm** [comment]
You probably didn't define the rules, please follow the vee-validate [guide here](https://vee-validate.logaretm.com/v4/guide/global-validators)

**Comment by timsayshey** [comment]
Yeah, I was under the impression that Vee-Validate would include basic validations by default. Do I need to define every rule? Even for basic things like `required` ?

**Comment by marina-mosti** [comment]
Additionally, the updated version of the plugin for fvl 3.x is not yet published. Those two versions should be incompatible

**Comment by logaretm** [comment]
> Do I need to define every rule? Even for basic things like `required`?

Yes, neither formulate nor vee-validate make any assumption about the rules you want to use as this would increase your bundle size unnecessarily which would slow your app down, this has been the case for a while now.

**Comment by timsayshey** [comment]
Well Formulate does include a set of default validations but I think you meant FormVueLate

**Comment by marina-mosti** [comment]
I'm closing this because of incompatible versions. Please use fvl 2 or wait for plugins to be updated for 3
