### ISSUE TITLE
Access validation errors outside of SchemaForm component

### ISSUE THREAD

**Issue by timsayshey** [formvuelate/formvuelate-plugin-vee-validate#17]
I want to display a list of all the validation errors on the page, not just under each input. ie

```
<SchemaForm schema="schema" />
<p>{{veevalidate.errors}}</p>
```

Is there a global object or something I need to import?

Thanks!

**Comment by timsayshey** [comment]
@marina-mosti - Can you tell me if this is possible? Thanks!

**Comment by logaretm** [comment]
This is not possible at the moment for the vee-validate plugin, but this discussion [here](https://github.com/formvuelate/formvuelate/discussions/180) is an RFC for a feature that is not implemented yet, feel free to provide feedback on the proposed API.

There is a workaround though, you could use [vee-validate's composition helpers](https://vee-validate.logaretm.com/v4/guide/composition-api/api-review#composition-helpers) to access what you need, note that it has to be in a child component of the schema form.

```vue
<SchemaForm schema="schema">
  <!-- custom component that uses useFormErrors -->
  <FormErrors />
</SchemaForm>
```

**Comment by timsayshey** [comment]
Thanks! Your workaround worked perfectly. Here's my code for anyone else:

Parent
```
<template lang="pug">
SchemaForm(
  :schema='schema'
)
  template(v-slot:afterForm)
    FormErrors(@errors='validationCallback')
</template>
```

FormErrors.vue

```
<template lang="pug">
div
</template>

<script lang="ts">
import { defineComponent, watch } from 'vue'
import { useFormErrors } from 'vee-validate'
export default defineComponent({
  name: 'FormErrors',
  emits: ['errors'],
  setup(props, { emit }) {
    const validationErrors = useFormErrors()
    watch(validationErrors, errors => {
      emit('errors', errors)
    })
  },
})
</script>
```
