### ISSUE TITLE
Computed form level validation-schema is not reactive

### ISSUE THREAD

**Issue by wesratcliff** [formvuelate/formvuelate-plugin-vee-validate#19]
**Describe the bug**
I am trying to make a computed form-level validation schema, but it does not seem to be reactive.

**To Reproduce**
```
it.only("preserves reactivity in computed schemas and validations", async () => {
  const toggle = ref("");
  const SchemaWithValidation = SchemaFormFactory([veeValidatePlugin()]);
  const schema = computed(() => {
    const computedSchema = {
      firstName: {
        label: "First Name",
        component: FormText,
      },
    };
    if (toggle.value === "REQUIRE_EMAIL") {
      return {
        ...computedSchema,
        email: {
          label: "Email",
          component: FormText,
        },
      };
    }

    return computedSchema;
  });

  const validationSchema = computed(() => {
    const computedSchema = {
      firstName: yup.string().required("NAME"),
    };
    if (toggle.value === "REQUIRE_EMAIL") {
      computedSchema.email = yup.string().email().required("EMAIL");
    }
    return yup.object().shape(computedSchema);
  });

  const wrapper = mount({
    template: `
    <SchemaWithValidation :schema="schema" :validation-schema="validationSchema">
      <template #afterForm="{ validation }">
        <span id="test">{{ validation }}</span>
        <button :disabled="!validation.meta.valid"></button>
      </template>
    </SchemaWithValidation>
  `,
    components: {
      SchemaWithValidation,
    },
    setup() {
      const formData = ref({});
      useSchemaForm(formData);

      return {
        schema,
        validationSchema,
      };
    },
  });

  // Only "firstName" shows
  let input = wrapper.findAllComponents(FormText);
  expect(input.length).toBe(1);

  toggle.value = "";
  await flushPromises();

  // Form is invalid (firstName is required)
  const button = wrapper.find("button");
  expect(button.element.disabled).toBe(true);

  // Fill in firstName
  input[0].setValue("name");
  await flushPromises();

  // Form is valid
  expect(button.element.disabled).toBe(false);

  // Show "email"
  toggle.value = "REQUIRE_EMAIL";
  await flushPromises();

  input = wrapper.findAllComponents(FormText);
  expect(input.length).toBe(2);

  // Touch email
  input[1].setValue("");
  await flushPromises();

  // ERROR Form is valid, but should be invalid?
  expect(button.element.disabled).toBe(true);
});
```

**Expected behavior**
When the toggle is set to "REQUIRE_EMAIL", which shows the email field and updates the form-level validation schema to require it, I expect the form to be invalid.

Additionally, "touching" the email field does not mark the form as invalid leading me to believe the computed validation schema is not reactive.

**System Info**
- FormVueLate version: 3.3.0
- @formvuelate/plugin-vee-validate version: 2.3.0 (vee-validate: 4.0.0-beta.16)

**Comment by marina-mosti** [comment]
Hi @wesratcliff can you provide reproduction in a code sandbox? There may be something in the jest/VTU here that is making noise

**Comment by wesratcliff** [comment]
Happy to @marina-mosti -- [here it is](https://codesandbox.io/s/fvl-conditional-schema-3x-forked-8hnz3?file=/src/App.vue).

**Comment by logaretm** [comment]
Did some digging, so the plugin tries to resolve the validation schema by getting the `validation-schema` attr off the Vue instance. The problem is that `attrs` in the [setup context is non-reactive](https://v3.vuejs.org/guide/composition-api-setup.html#props), this means the plugin has no way to detect any changes to that attribute/prop.

I have an idea here: we could allow plugins to augment the `SchemaForm` with their own props and giving them access as `props` in the `baseReturns` object. 

That would require a `beforeSetup` hook or cycle we need expose to plugins to allow them to do such things (outside the setup), as we mentioned in https://github.com/formvuelate/formvuelate/discussions/204

@marina-mosti **WDYT?**

**Comment by marina-mosti** [comment]
@logaretm Agreed. Pushing to get the monorepo ready on https://github.com/formvuelate/formvuelate/pull/212 as discussed. This will have to wait until its set up so we can test easier

**Comment by wesratcliff** [comment]
Thank you for taking a look @marina-mosti and @logaretm.

I modified a local copy of the plugin to fit my use case and can confirm that passing the validation schema in as a reactive property works as intended!
