### ISSUE TITLE
[QUESTION] How to use globally imported components with the plugin?

### ISSUE THREAD

**Issue by dheimoz** [formvuelate/formvuelate-plugin-vee-validate#4]
Hello Team:

I might have found a bug, but first I want to make sure I have followed the instructions correctly. Documentation points out that the Component can be a string, provided it is globally registered:
_"You can use the name of the component as a String instead, for example 'FormText', but be aware that the component needs to either be imported globally, or in your file first."_

I have taken the BaseInput.vue component, added the validation prop and globally registered in main.js

`import { createApp } from "vue";
import BaseInput from "@/path/to/BaseInput";
app.component("base-text", BaseInput);
app.mount("#app");`

Now the tricky part, should I use the string 'base-text' with the normal SchemaForm the component is rendered:

`const schema = shallowRef({
      banco: {
        component: "base-text",
        label: "A label",
      },
    });`
![image](https://user-images.githubusercontent.com/382153/100863388-1f31f200-345a-11eb-9fea-8d292e26cfa3.png)

However, if I create the SchemaFormWithPlugins with SchemaFormFactory:

```
const SchemaFormWithPlugins = SchemaFormFactory([VeeValidatePlugin()]);
export default{
 components: {
    SchemaFormWithPlugins,
 }
setup(){
const schema = shallowRef({
      banco: {
        component: "base-text",
        label: "A label",
      },
    })
return {schema}
}
}
````
The Component does not render.

![image](https://user-images.githubusercontent.com/382153/100862785-38866e80-3459-11eb-9f8d-0af9f2a747e4.png)

Nonetheless, a locally registered BaseInput in SchemaFormWithPlugins works as expected:

```
import BaseInput from "@/path/to/BaseInput";
export default {
components: {
    BaseInput,
},
setup(){
const schema = shallowRef({
      banco: {
        component: BaseInput,
        label: "A label",
      },
    })
return {schema}
}

}
```

![image](https://user-images.githubusercontent.com/382153/100863086-a6cb3100-3459-11eb-81ea-15f4793db71b.png)

I wonder if I messing something up.

Thanks team.

**Comment by marina-mosti** [comment]
I don't see anything obvious at first glance, @logaretm what do you think?
@dheimoz can you provide a minimal reproduction repo please, and any console errors?

**Comment by dheimoz** [comment]
Hello @marina-mosti , no console errors. Let me create the repo.
Thanks for the quick response.

**Comment by dheimoz** [comment]
Hello @marina-mosti and @logaretm . Sorry for the delay.
Here is the minimal repository where you will find the issue
https://github.com/dheimoz/vee-validate-min-repo

Essentially it is the default vue create app with vue router. 

I register BaseInput.vue as "base-text" in main.js

In About I placed the working global component with Schema Form. In the schema as component I pass the string.

In Home I created the SchemaFormWithVee with SchemaFactury and the VueeValidatePlugin.

Should I try to use the String for the component, nothing is rendered and no console logs are shown.

In comments you will find the Local BaseInput registration. Then, if you uncomment those lines and use the Component Name in the schema, it will be rendered.

I hope this helps to troubleshoot the issue, I will try to narrow down the problem to SchemaWizard.js or the VeeValidatePlugin.

Thank you.

**Comment by logaretm** [comment]
@marina-mosti @dheimoz I investigated and it has something to do with this RFC

https://github.com/vuejs/rfcs/blob/master/active-rfcs/0008-render-function-api-change.md#context-free-vnodes

Basically, the `h` function cannot render elements as a string and should be only used for native elements. A quick fix is to wrap the `h` call with `resolveDynamicComponent`.

I will create a PR for this shortly.

**Comment by dheimoz** [comment]
hey @logaretm thank you very much for taking the time to review this. Looking forward for your PR.
This efforts are making Formvuelate better.
