### ISSUE TITLE
Vee-vaidate crashes when using the nested "subform" array schema

### ISSUE THREAD

**Issue by D3m1urg0** [formvuelate/formvuelate-plugin-vee-validate#6]
**Describe the bug**
The function `getFromPath` in Vee-validate crashes when reaches a nested schema-form in the array-schema example

```
 {
        component: "schema-form", //SchemaForm,
        model: "subform",
        schema: [
          {
            // validations: yup.string().required(),
            component: "text-input", //FormText,
            label: "Work address",
            model: "address"
          },
          {
            // validations: yup.string().required(),
            component: "text-input", //FormText,
            label: "Work phone",
            model: "phone"
          }
        ]
      }
```

on the other hand FormVueLate wont recognize the `nested.path.model` syntax for nested values of Vee Validate

**To Reproduce**

Run the "array based schema example" with a "vee-validate-plugin" component syntax

**Expected behavior**
Vee validate ignores the scheda-form level without crashing

**System Info**
- FormVueLate version:      "formvuelate": "^2.0.0",
- plugins being used with versions:      "@formvuelate/plugin-vee-validate": "^1.0.3",

**Additional context**

**Comment by logaretm** [comment]
This is interesting as vee-validate doesn't really have a concept of nested forms. I will see what I can do.

I think I can virtually nest the fields using the vee-validate path API.

**Comment by D3m1urg0** [comment]
Actually vee validate have this:
https://vee-validate.logaretm.com/v4/guide/nested-objects-and-arrays#nested-objects

And the function that looks for path hidden in the name is the cause of this crash
